name: candi
backbone: candi-dit
parameterization: mean
time_conditioning: true
T: 0
causal_attention: False
adaLN: True
diffusion_type: diffusion
loss_type: diffusion
step_size: 1.0
mixed_coeff: 0.5
max_percentile: 0.25
min_percentile: 0.01
sigma_min: 0.01
sigma_max: 2.0
temp: 1.0
pure_continuous: False
sampler: cached
is_embed: False
use_percentile_scheduling: True
ignore_bos: False
